server:
  port: 9000

---
spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      settings:
        trace: on
  sql:
    init:
      mode: always
      data-locations: classpath:data-h2.sql
      schema-locations: classpath:schema-h2.sql
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
    show-sql: true
    hibernate:
      id:
        new_generator_mappings: true
      ddl-auto: none
---
spring:
  profiles:
    active: prod
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://cornelius.db.elephantsql.com/cxomqbfc
    username: cxomqbfc
    password: NVQNxWPvzqNGDnuDiCxYJIYKNj0fvwG0
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      data-locations: classpath:data-postgres.sql
      schema-locations: classpath:schema-postgres.sql
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      id:
        new_generator_mappings: true
      ddl-auto: none